#!/bin/sh
# Fast pre-commit gate mirroring the CI "distribution-metadata" job:
# first-party license text and crates.io publication metadata must be present.
set -e
cd "$(git rev-parse --show-toplevel)"
python3 packaging/verify.py --require-distribution
